In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import os
import matplotlib.pyplot as plt

from transformers import AutoTokenizer, TFBertModel
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from imblearn.under_sampling import RandomUnderSampler
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Input, Dense

In [2]:
cwd = os.getcwd()
cwd

'C:\\Users\\LENOVO\\GitHub\\capstone_bangkit'

In [3]:
# test_model = tf.saved_model.load('model/model_2023-11-15')

In [4]:
test_model = tf.keras.models.load_model('model/model_2023-11-15', custom_objects={"TFBertModel": TFBertModel})

In [5]:
test_model.summary()

AttributeError: '_UserObject' object has no attribute 'summary'

In [6]:
test_model

<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x251e53228e0>

In [7]:
test_model.summary()

AttributeError: '_UserObject' object has no attribute 'summary'

In [8]:
test = os.path.join(cwd, 'content')
os.listdir(test)

['archive', 'cnn_content_2023-11-11.csv']

In [9]:
real_df = pd.read_csv(os.path.join(test, 'cnn_content_2023-11-11.csv'))
real_df

berita  \
0   Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   
1   Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   
2   Mahfud lekat dengan inisial MD yang tersemat d...   
3   Perebutan tiket atau yang populer dengan istil...   
4   Riuh Pemilu 2024 tak cuma seputar capres-cawap...   
5   Menteri Kesehatan (Menkes) Budi Gunadi Sadikin...   
6   Bakal calon presiden Koalisi Perubahan Anies B...   
7   Menteri Pertahanan Prabowo Subianto menyebut a...   
8   Sembilan hakim Mahkamah Konstitusi (MK) dikena...   
9   Undang-undang Nomor 7 Tahun 2017 tentang Pemil...   
10  Undang-undang Nomor 7 Tahun 2017 tentang Pemil...   
11  Seseorang yang mengajak orang lain agar tidak ...   
12  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   
13  Ikatan Dokter Indonesia (IDI) menyatakan kasus...   
14  Kapolri Jenderal Listyo Sigit Prabowo memberik...   
15  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   
16  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   
17  Komisaris PT Pertamina (Persero) Basuki Tjahaj...   
18  Koalisi Indonesia Maju (KIM) resmi mengumumkan...   
19  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...   

                                                judul         sumber  \
0   MKMK Perintahkan Saldi Isra Gelar Pemilihan Pe...  CNN Indonesia   
1   Putusan MKMK: Anwar Usman Langgar Etik Berat, ...  CNN Indonesia   
2                  Asal Usul MD di Buntut Nama Mahfud  CNN Indonesia   
3   Mereka yang Tersingkir di War Tiket Cawapres 2024  CNN Indonesia   
4        Pertarungan Caleg di Dapil Neraka Jakarta II  CNN Indonesia   
5   Menkes Susun UU Baru: Pengguna Napza yang Saki...  CNN Indonesia   
6   Anies Respons Tim Prabowo-Gibran Gaet Khofifah...  CNN Indonesia   
7   Prabowo Sebut Ada Menteri Neoliberal di Kabine...  CNN Indonesia   
8   9 Hakim MK Kena Sanksi Teguran Lisan Buntut RP...  CNN Indonesia   
9   Pemilu: Pemda Dilarang Bertindak yang Merugika...  CNN Indonesia   
10  Hakim MK hingga Komisaris BUMN Dilarang Ikut K...  CNN Indonesia   
11  UU Pemilu: Ajak Orang Lain Golput Bisa Disanks...  CNN Indonesia   
12  Putusan MKMK: Arief Hidayat Langgar Etik Renda...  CNN Indonesia   
13    IDI: Kasus Cacar Monyet di RI Bertambah Jadi 35  CNN Indonesia   
14  Kapolri Beri Kenaikan Pangkat Luar Biasa ke Pe...  CNN Indonesia   
15  Putusan MKMK: Saldi Isra Tidak Langgar Etik so...  CNN Indonesia   
16  Putusan MKMK: 9 Hakim MK Langgar Etik Bocor In...  CNN Indonesia   
17  Ahok Buka Suara Usai Diperiksa KPK 6 Jam di Ka...  CNN Indonesia   
18  Menakar Kekuatan Struktur Gemuk Bertabur Elite...  CNN Indonesia   
19  Apakah Putusan Etik Anwar Cs Bisa Gugurkan Put...  CNN Indonesia   

                            tanggal     jenis  
0    Selasa, 07 Nov 2023 18:27 WIB   nasional  
1    Selasa, 07 Nov 2023 18:20 WIB   nasional  
2     Kamis, 02 Nov 2023 16:17 WIB   nasional  
3     Jumat, 27 Okt 2023 10:12 WIB   nasional  
4      Rabu, 11 Okt 2023 07:15 WIB   nasional  
5    Selasa, 07 Nov 2023 18:03 WIB   nasional  
6    Selasa, 07 Nov 2023 17:54 WIB   nasional  
7    Selasa, 07 Nov 2023 17:45 WIB   nasional  
8    Selasa, 07 Nov 2023 17:40 WIB   nasional  
9     Senin, 06 Nov 2023 10:42 WIB   nasional  
10    Senin, 30 Okt 2023 07:15 WIB   nasional  
11   Selasa, 24 Okt 2023 06:36 WIB   nasional  
12   Selasa, 07 Nov 2023 17:38 WIB   nasional  
13   Selasa, 07 Nov 2023 17:29 WIB   nasional  
14   Selasa, 07 Nov 2023 17:25 WIB   nasional  
15   Selasa, 07 Nov 2023 17:09 WIB   nasional  
16   Selasa, 07 Nov 2023 16:45 WIB   nasional  
17   Selasa, 07 Nov 2023 16:37 WIB   nasional  
18   Selasa, 07 Nov 2023 09:38 WIB   nasional  
19    Senin, 06 Nov 2023 10:20 WIB   nasional

In [10]:
df = real_df[['berita']]

In [11]:
test_twt = {
    'berita' : ["lewat di tl aku, dan aku kaget. Aku kira RS ini dibangunnya sama pemerintah kita ternyata pembangunannya dari uang donasi masyarakat kita toh aku nangis banget pas liat videonya juga", "Jog dalam kota kecepatan 80km/jam dan nerobos lampu merah. Dimf bawah ini juga ada cctv kalau ojol berhenti dipinggir anda tabrak, giliran diminta ganti rugi merasa diperas. Playing victim sekali ya wkwkwk", "Peta hubungan diplomatik Israel dengan negara-negara dunia. Hanya ada satu negara dengan perekonomian raksasa ber-GDP di atas $1 triliun yang belum pernah menjalin relasi sama Israel. Yep, Indonesia.", "Pernah penasaran ga sih kenapa Nabi & Rasul itu diutusnya di Arab, Jordan, & Mesir padahal dunia ini luas? Gambar ini sedikit banyak menjelaskan", "Ada perbedaan pada momen kelahiran anak kedua pasangan Atta Halilintar dan Aurel Hermansyah. Pasalnya, semua orangtua atau nenek dari Ameena dan putri keduanya turut hadir. Tentunya hal ini memberikan kebahagiaan bagi Atta dan Aurel. Apalagi mengingat saat momen Ameena lahir, tak seramai kelahiran anak keduanya ini. Saat ditemui di RSIA Bunda, Jakarta Pusat, Senin (13/11) Atta Halilintar merasa momen kelahiran adik Ameena seperti mimpi yang menjadi kenyataan baginya. “Ini udah kayak mimpi jadi nyata buat saya sama Aurel karena semua orangtua bisa hadir. Kemarin (anak pertama) lahiran kan pas Covid ya jadi nggak semua bisa hadir,” ungkap Atta Halilintar. 1. Didampingi Orang-Orang Tersayang Diketahui Dalam foto yang dibagikan di akun media sosial Atta Halilintar, ayah dan ibunya tampak hadir di rumah sakit. Begitu juga dengan orangtua Aurel, Anang Hermansyah dan Ashanty serta Krisdayanti yang tak ingin ketinggalan momen tersebut. Atta pun mengatakan, orangtua dan mertuanya hadir di rumah sakit menanti detik-detik kelahiran anak keduanya. Bahkan mereka juga rela berangkat dini hari ke rumah sakit. 2. Berkumpul Sejak Subuh “Semua mendoakan, semua lengkap semuanya udah ada dari pagi ngumpul di RSIA Bunda mengantar ke rumah sakit dari jam 03.00 WIB terus salat subuh bareng juga,” ujarnya. Ia menilai doa dari orangtuanya dan mertuanya menjadi kekuatan bagi Aurel Hermansyah. “Jadi menurutku doa dari semua jadi menguatkan juga ya. Semua sudah nggak sabar menyambut cucu keduanya,” tukasnya."] 
}

df_test_twt = pd.DataFrame(test_twt)
df_test_twt

df = pd.concat([real_df[['berita']], df_test_twt], ignore_index=True)
df

berita
0   Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
1   Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
2   Mahfud lekat dengan inisial MD yang tersemat d...
3   Perebutan tiket atau yang populer dengan istil...
4   Riuh Pemilu 2024 tak cuma seputar capres-cawap...
5   Menteri Kesehatan (Menkes) Budi Gunadi Sadikin...
6   Bakal calon presiden Koalisi Perubahan Anies B...
7   Menteri Pertahanan Prabowo Subianto menyebut a...
8   Sembilan hakim Mahkamah Konstitusi (MK) dikena...
9   Undang-undang Nomor 7 Tahun 2017 tentang Pemil...
10  Undang-undang Nomor 7 Tahun 2017 tentang Pemil...
11  Seseorang yang mengajak orang lain agar tidak ...
12  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
13  Ikatan Dokter Indonesia (IDI) menyatakan kasus...
14  Kapolri Jenderal Listyo Sigit Prabowo memberik...
15  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
16  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
17  Komisaris PT Pertamina (Persero) Basuki Tjahaj...
18  Koalisi Indonesia Maju (KIM) resmi mengumumkan...
19  Majelis Kehormatan Mahkamah Konstitusi (MKMK) ...
20  lewat di tl aku, dan aku kaget. Aku kira RS in...
21  Jog dalam kota kecepatan 80km/jam dan nerobos ...
22  Peta hubungan diplomatik Israel dengan negara-...
23  Pernah penasaran ga sih kenapa Nabi & Rasul it...
24  Ada perbedaan pada momen kelahiran anak kedua ...

In [12]:
# datapath = os.path.join(cwd, 'dataset')

# df = pd.read_excel(os.path.join(datapath, 'all_cleaned.xlsx'))
# df = df[['berita', 'label']]

df.drop_duplicates(inplace=True)
df.dropna(inplace = True)

df_test = df

max_len = 70
model_name = 'indobenchmark/indobert-base-p1'
tokenizer = AutoTokenizer.from_pretrained(model_name)

X_train = tokenizer(
    text=df_test['berita'].tolist(),
    add_special_tokens=True,
    max_length=max_len,
    truncation=True,
    padding=True,
    return_tensors='tf',
    return_token_type_ids=False,
    return_attention_mask=True,
    verbose=True
)

X_train

{'input_ids': <tf.Tensor: shape=(25, 70), dtype=int32, numpy=
array([[    2,  6810,  9293, ...,   680, 30471,     3],
       [    2,  6810,  9293, ...,  4887,  7343,     3],
       [    2, 20469, 26243, ...,   126,  1328,     3],
       ...,
       [    2,  2577,  1314, ...,     0,     0,     0],
       [    2,   746,  5728, ...,     0,     0,     0],
       [    2,   176,  2217, ...,   102,  6455,     3]])>, 'attention_mask': <tf.Tensor: shape=(25, 70), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]])>}

In [13]:
X_train[20]

Encoding(num_tokens=70, attributes=[ids, type_ids, tokens, offsets, attention_mask, special_tokens_mask, overflowing])

In [14]:
df.iloc[20]['berita'].split()

['lewat',
 'di',
 'tl',
 'aku,',
 'dan',
 'aku',
 'kaget.',
 'Aku',
 'kira',
 'RS',
 'ini',
 'dibangunnya',
 'sama',
 'pemerintah',
 'kita',
 'ternyata',
 'pembangunannya',
 'dari',
 'uang',
 'donasi',
 'masyarakat',
 'kita',
 'toh',
 'aku',
 'nangis',
 'banget',
 'pas',
 'liat',
 'videonya',
 'juga']

In [15]:
X_train['input_ids'][20]

<tf.Tensor: shape=(70,), dtype=int32, numpy=
array([    2,  2145,    26,  9480,   304, 30468,    41,   304,  7950,
       30470,   304,  5157,  3935,    92,  3887,    57,   500,   877,
         219,  1369, 24734,    98,   988, 21781,   552,   219,  8027,
         304, 15089,  2174,   280,  4961, 21370,   186,     3,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0])>

In [16]:
X_train['attention_mask'][20]

<tf.Tensor: shape=(70,), dtype=int32, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])>

In [17]:
input_ids = tf.TensorSpec.from_tensor(X_train['input_ids'], name = 'input_ids')
attention_mask = tf.TensorSpec.from_tensor(X_train['attention_mask'], name = 'attention_mask')

In [18]:
df.berita[14]

'Kapolri Jenderal Listyo Sigit Prabowo memberikan penghargaan Kenaikan Pangkat Luar Biasa (KPLB) kepada 47 personel Satgas Damai Cartenz. Penghargaan KPLB tersebut diberikan langsung oleh Kapolri secara simbolis kepada tiga perwakilan Satgas Damai Cartenz yakni Ipda Erlang Surya Agustian, Bripka Suhardi, dan Bharatu Muhrijan Tangahu di Hotel Borobudur, Jakarta, Selasa (7/11).    Kepala Biro Psikologi Sumber Daya Manusia (SDM) Polri Brigjen Kristiyono mengatakan penghargaan diberikan Listyo terhadap seluruh anggota yang bertugas melawan Kelompok Kriminal Bersenjata (KKB) di wilayah Papua. "Itu bentuk apresiasi dari pimpinan terhadap kinerja anggota yang telah memberikan tenaga dan pikirannya untuk melakukan kegiatan pengamanan di wilayah Papua," kata Kristiyono usai Rapat Koordinasi Pembinaan (Rakorbin) SDM Polri di Hotel Borobudur. Kenaikan pangkat luar biasa itu sebagai penghargaan atas keberhasilan Satgas Damai Cartenz ketika menggerebek markas KKB pimpinan Ananias Ati Mimin di wilay

In [19]:
predicted = test_model([X_train['input_ids'], X_train['attention_mask']])
y_predicted = [1 if pred >= 0.5 else 0 for pred in predicted]
y_predicted, predicted

([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1],
 <tf.Tensor: shape=(25, 1), dtype=float32, numpy=
 array([[0.21018264],
        [0.06515755],
        [0.81459844],
        [0.20085591],
        [0.08414769],
        [0.12640078],
        [0.01411121],
        [0.06522382],
        [0.37205437],
        [0.44566485],
        [0.05212738],
        [0.49168324],
        [0.3052911 ],
        [0.82749903],
        [0.5306682 ],
        [0.30376476],
        [0.05958658],
        [0.5941604 ],
        [0.01425847],
        [0.19136627],
        [0.989747  ],
        [0.9941998 ],
        [0.88260114],
        [0.9957684 ],
        [0.6108307 ]], dtype=float32)>)